# config/BUILD

package(default_visibility = ["//visibility:public"])

constraint_setting(name = "board")

constraint_value(
    name = "pca10040",
    constraint_setting = ":board",
)

constraint_value(
    name = "pca10056",
    constraint_setting = ":board",
)

constraint_value(
    name = "pca10100",
    constraint_setting = ":board",
)
