# config/BUILD

package(default_visibility = ["//visibility:public"])

config_setting(
    name = "pca10040",
    values = {
        "platforms": "@nRF5//platforms:pca10040",
    },
)

config_setting(
    name = "pca10056",
    values = {
        "platforms": "@nRF5//platforms:pca10056",
    },
)

config_setting(
    name = "pca10100",
    values = {
        "platforms": "@nRF5//platforms:pca10100",
    },
)
