load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "config",
    srcs = ["sdk_config.h"],
    hdrs = ["sdk_config.h"],
    includes = ["."],
)
